# backend/managers/world/level_base.py
"""Abstract base class for level generators."""

from abc import ABC, abstractmethod
from typing import Dict, Any, Optional, List
from models.Room import Room


class LevelGenerator(ABC):
    """
    Abstract base class for level generators.

    Each level in the game world is generated by a subclass of this class.
    The world generator calls these methods in order to build the complete world.
    """

    # Level metadata - subclasses should override these
    level_number: int = 0
    level_name: str = "Unknown Level"

    def __init__(self) -> None:
        """Initialize the level generator."""
        self._rooms: Dict[str, Room] = {}

    @property
    def rooms(self) -> Dict[str, Room]:
        """Get the rooms generated by this level."""
        return self._rooms

    @property
    def room_ids(self) -> List[str]:
        """Get a list of room IDs in this level."""
        return list(self._rooms.keys())

    @abstractmethod
    def generate_rooms(self) -> Dict[str, Room]:
        """
        Generate all rooms for this level.

        Returns:
            Dict mapping room_id to Room objects for this level.
        """
        pass

    @abstractmethod
    def connect_internal_exits(self) -> None:
        """
        Connect exits between rooms within this level.

        This should only set up connections between rooms in this level.
        Cross-level connections are handled by configure_transitions().
        """
        pass

    @abstractmethod
    def add_items(self) -> None:
        """
        Add all items to rooms in this level.

        This includes:
        - Regular items (Item)
        - Stateful items (StatefulItem) - puzzles, switches, etc.
        - Container items (ContainerItem) - chests, cages, etc.
        - Weapons (Weapon)
        """
        pass

    @abstractmethod
    def spawn_mobs(self, mob_manager: Any) -> None:
        """
        Spawn mobs for this level.

        Args:
            mob_manager: The MobManager instance for spawning mobs.
        """
        pass

    def configure_npc_interactions(self, mob_manager: Any) -> None:
        """
        Configure NPC interactions for mobs in this level.

        Override this method to set up accepts_item, speech responses,
        and other NPC-specific behaviors.

        Args:
            mob_manager: The MobManager instance.
        """
        pass

    def get_room(self, room_id: str) -> Optional[Room]:
        """
        Get a room by ID from this level.

        Args:
            room_id: The room ID to look up.

        Returns:
            The Room object, or None if not found.
        """
        return self._rooms.get(room_id)

    def has_room(self, room_id: str) -> bool:
        """
        Check if this level contains a room with the given ID.

        Args:
            room_id: The room ID to check.

        Returns:
            True if the room exists in this level.
        """
        return room_id in self._rooms

    def spawn_mob_in_room(
        self, mob_manager: Any, mob_type: str, room_id: str
    ) -> Optional[Any]:
        """
        Helper method to spawn a mob in a room.

        Args:
            mob_manager: The MobManager instance.
            mob_type: The mob definition ID to spawn.
            room_id: The room ID to spawn the mob in.

        Returns:
            The spawned mob, or None if the room doesn't exist.
        """
        if room_id not in self._rooms:
            return None

        mob_manager.spawn_mob(mob_type, room_id)
        # Get the most recently spawned mob
        mob_ids = list(mob_manager.mobs.keys())
        if mob_ids:
            mob = mob_manager.mobs.get(mob_ids[-1])
            if mob:
                self._rooms[room_id].add_item(mob)
                return mob
        return None
