# backend/managers/mob_definitions.py

from typing import Dict, Any
from models.Item import Item
from models.Weapon import Weapon


def get_mob_definitions() -> Dict[str, Dict[str, Any]]:
    """
    Define mob templates for the Valley of Barovia.

    Returns:
        dict: Dictionary of mob_definition_id -> mob template
    """

    # Define loot items
    dagger = Weapon(
        name="dagger",
        id="dagger",
        description="A simple iron dagger.",
        weight=1,
        value=5,
        takeable=True,
        damage=4,
        min_level="Neophyte",
        min_strength=0,
        min_dexterity=5,
    )

    coin = Item(
        name="coin",
        id="coin",
        description="A tarnished silver coin bearing Strahd's visage.",
        weight=1,
        value=10,
        takeable=True,
    )

    fang = Item(
        name="fang",
        id="fang",
        description="A razor-sharp vampire fang.",
        weight=1,
        value=25,
        takeable=True,
    )

    pelt = Item(
        name="pelt",
        id="pelt",
        description="A thick wolf pelt, still warm.",
        weight=2,
        value=15,
        takeable=True,
    )

    skull = Item(
        name="skull",
        id="skull",
        description="A yellowed human skull is here, its empty eye sockets staring at you.",
        weight=1,
        value=3,
        takeable=True,
    )

    claw = Item(
        name="claw",
        id="claw",
        description="A curved ghoul claw, blackened with decay.",
        weight=1,
        value=8,
        takeable=True,
    )

    essence = Item(
        name="essence",
        id="essence",
        description="A vial of shadowy essence that swirls with darkness.",
        weight=1,
        value=30,
        takeable=True,
    )

    heart = Item(
        name="heart",
        id="mob_heart",
        description="A still-beating heart, impossibly alive.",
        weight=1,
        value=50,
        takeable=True,
    )

    return {
        # ===== VILLAGE OF BAROVIA =====
        # Peaceful peasant - frightened villager
        "peasant": {
            "name": "peasant",
            "description": "A haggard peasant with hollow eyes shuffles past, avoiding your gaze.",
            "strength": 10,
            "dexterity": 8,
            "max_stamina": 30,
            "damage": 1,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": ["square", "road", "shop"],
            "movement_interval": 150,
            "loot_table": [
                {"item": coin, "chance": 0.3},
            ],
            "instant_death": False,
            "point_value": 0,
            "pronouns": "he",
        },
        # Barkeep at Blood of the Vine
        "barkeep": {
            "name": "barkeep",
            "description": "The barkeep wearily polishes a glass, staring at nothing.",
            "strength": 15,
            "dexterity": 12,
            "max_stamina": 50,
            "damage": 3,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": coin, "chance": 0.5},
            ],
            "instant_death": False,
            "point_value": 0,
            "pronouns": "he",
        },
        # Village priest
        "priest": {
            "name": "priest",
            "description": "The village priest, Father Donavich, kneels in prayer, his robes tattered and stained.",
            "strength": 12,
            "dexterity": 10,
            "max_stamina": 40,
            "damage": 2,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [],
            "instant_death": False,
            "point_value": 0,
            "pronouns": "he",
        },
        # Bildrath the greedy shopkeeper
        "bildrath": {
            "name": "Bildrath",
            "description": "Bildrath, a portly man with beady eyes and greasy hair, watches your every move with suspicion.",
            "strength": 20,
            "dexterity": 15,
            "max_stamina": 60,
            "damage": 5,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": coin, "chance": 1.0},
                {"item": coin, "chance": 0.8},
                {"item": coin, "chance": 0.6},
            ],
            "instant_death": False,
            "point_value": 30,
            "pronouns": "he",
        },
        # Zombie - moderate threat in graveyard
        "zombie": {
            "name": "zombie",
            "description": "A zombie lurches toward you, rotting flesh hanging from its shambling corpse.",
            "strength": 25,
            "dexterity": 8,
            "max_stamina": 70,
            "damage": 8,
            "aggressive": True,
            "aggro_delay_min": 2,
            "aggro_delay_max": 4,
            "patrol_rooms": ["graveyard"],
            "movement_interval": 0,
            "loot_table": [
                {"item": skull, "chance": 0.6},
                {"item": coin, "chance": 0.2},
            ],
            "instant_death": False,
            "point_value": 40,
            "pronouns": "it",
        },
        # Ghoul - dangerous in crypt
        "ghoul": {
            "name": "ghoul",
            "description": "A ghoul crouches in the shadows, its hunched form bristling with elongated claws, hungry eyes fixed on you.",
            "strength": 35,
            "dexterity": 25,
            "max_stamina": 80,
            "damage": 12,
            "aggressive": True,
            "aggro_delay_min": 1,
            "aggro_delay_max": 2,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": claw, "chance": 0.7},
                {"item": coin, "chance": 0.4},
            ],
            "instant_death": False,
            "point_value": 75,
            "pronouns": "it",
        },
        # ===== SVALICH WOODS =====
        # Wolf - aggressive pack hunter
        "wolf": {
            "name": "wolf",
            "description": "A large grey wolf with hungry eyes watches you, lips pulled back in a snarl.",
            "strength": 30,
            "dexterity": 35,
            "max_stamina": 60,
            "damage": 9,
            "aggressive": True,
            "aggro_delay_min": 1,
            "aggro_delay_max": 3,
            "patrol_rooms": ["woods", "clearing", "road", "crossroads"],
            "movement_interval": 60,
            "loot_table": [
                {"item": pelt, "chance": 0.8},
            ],
            "instant_death": False,
            "point_value": 50,
            "pronouns": "it",
        },
        # Vistani trader
        "vistani": {
            "name": "vistani",
            "description": "A colorfully dressed Vistani eyes you with knowing amusement.",
            "strength": 20,
            "dexterity": 25,
            "max_stamina": 60,
            "damage": 6,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": coin, "chance": 0.6},
                {"item": coin, "chance": 0.4},
            ],
            "instant_death": False,
            "point_value": 20,
            "pronouns": "she",
        },
        # Madam Eva - fortune teller
        "seer": {
            "name": "seer",
            "description": "Madam Eva, an ancient seer with milky eyes, sits before a deck of worn cards.",
            "strength": 8,
            "dexterity": 10,
            "max_stamina": 30,
            "damage": 1,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [],
            "instant_death": False,
            "point_value": 0,
            "pronouns": "she",
        },
        # Bat swarm
        "bats": {
            "name": "bats",
            "description": "A swarm of bats hangs from the ceiling, their tiny eyes glinting.",
            "strength": 10,
            "dexterity": 40,
            "max_stamina": 25,
            "damage": 3,
            "aggressive": True,
            "aggro_delay_min": 3,
            "aggro_delay_max": 6,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [],
            "instant_death": False,
            "point_value": 15,
            "pronouns": "they",
        },
        # ===== OLD BONEGRINDER =====
        # Morgantha the hag - BOSS
        "hag": {
            "name": "hag",
            "description": "The hag Morgantha, a hideous crone with grey-green skin and needle teeth, grins at you with malevolent glee.",
            "strength": 50,
            "dexterity": 35,
            "max_stamina": 150,
            "damage": 18,
            "aggressive": True,
            "aggro_delay_min": 2,
            "aggro_delay_max": 4,
            "patrol_rooms": ["mill", "kitchen"],
            "movement_interval": 100,
            "loot_table": [
                {"item": essence, "chance": 0.9},
                {"item": coin, "chance": 0.8},
                {"item": coin, "chance": 0.6},
            ],
            "instant_death": False,
            "point_value": 200,
            "pronouns": "she",
        },
        # Hag daughter
        "daughter": {
            "name": "daughter",
            "description": "Morgantha's daughter, a younger hag with stringy hair and a cruel smile, lurks nearby.",
            "strength": 40,
            "dexterity": 30,
            "max_stamina": 100,
            "damage": 14,
            "aggressive": True,
            "aggro_delay_min": 1,
            "aggro_delay_max": 3,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": essence, "chance": 0.6},
                {"item": coin, "chance": 0.5},
            ],
            "instant_death": False,
            "point_value": 120,
            "pronouns": "she",
        },
        # Wereraven spy
        "raven": {
            "name": "raven",
            "description": "A large raven with unusually intelligent eyes watches from a perch. Something about this bird seems... unnatural.",
            "strength": 15,
            "dexterity": 40,
            "max_stamina": 40,
            "damage": 4,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [],
            "instant_death": False,
            "point_value": 0,
            "pronouns": "it",
        },
        # ===== ARGYNVOSTHOLT =====
        # Undead knight revenant
        "revenant": {
            "name": "revenant",
            "description": "A spectral revenant in tarnished armor stands eternal vigil, sword at ready.",
            "strength": 55,
            "dexterity": 30,
            "max_stamina": 140,
            "damage": 16,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": ["hall", "quarters"],
            "movement_interval": 200,
            "loot_table": [
                {"item": coin, "chance": 0.8},
                {"item": coin, "chance": 0.6},
            ],
            "instant_death": False,
            "point_value": 150,
            "pronouns": "he",
        },
        # Weeping phantom
        "phantom": {
            "name": "phantom",
            "description": "A translucent phantom drifts past, weeping silently for losses long past.",
            "strength": 20,
            "dexterity": 45,
            "max_stamina": 50,
            "damage": 8,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": ["hall", "approach"],
            "movement_interval": 150,
            "loot_table": [
                {"item": essence, "chance": 0.4},
            ],
            "instant_death": False,
            "point_value": 30,
            "pronouns": "it",
        },
        # Hostile specter
        "specter": {
            "name": "specter",
            "description": "A specter, a hateful spirit wreathed in darkness, shrieks with rage at the living.",
            "strength": 35,
            "dexterity": 40,
            "max_stamina": 70,
            "damage": 12,
            "aggressive": True,
            "aggro_delay_min": 0,
            "aggro_delay_max": 1,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": essence, "chance": 0.7},
            ],
            "instant_death": False,
            "point_value": 80,
            "pronouns": "it",
        },
        # ===== VALLAKI =====
        # Town guard
        "guard": {
            "name": "guard",
            "description": "A Vallaki guard in threadbare uniform watches with suspicious eyes.",
            "strength": 30,
            "dexterity": 25,
            "max_stamina": 80,
            "damage": 10,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": ["towngate", "street", "stockyard"],
            "movement_interval": 100,
            "loot_table": [
                {"item": dagger, "chance": 0.4},
                {"item": coin, "chance": 0.6},
            ],
            "instant_death": False,
            "point_value": 60,
            "pronouns": "he",
        },
        # Baron Vallakovich
        "baron": {
            "name": "baron",
            "description": "Baron Vallakovich paces nervously, muttering about mandatory happiness.",
            "strength": 25,
            "dexterity": 20,
            "max_stamina": 100,
            "damage": 8,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": coin, "chance": 1.0},
                {"item": coin, "chance": 0.8},
                {"item": coin, "chance": 0.6},
            ],
            "instant_death": False,
            "point_value": 100,
            "pronouns": "he",
        },
        # Wereraven ally
        "wereraven": {
            "name": "wereraven",
            "description": "A dark-haired man called Muriel nods knowingly at you, his sharp features almost bird-like.",
            "strength": 35,
            "dexterity": 40,
            "max_stamina": 90,
            "damage": 11,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [],
            "instant_death": False,
            "point_value": 0,
            "pronouns": "he",
        },
        # Vampire spawn
        "spawn": {
            "name": "spawn",
            "description": "A vampire spawn, pale with red-rimmed eyes and bared fangs, hisses at you.",
            "strength": 45,
            "dexterity": 38,
            "max_stamina": 100,
            "damage": 14,
            "aggressive": True,
            "aggro_delay_min": 1,
            "aggro_delay_max": 2,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": fang, "chance": 0.8},
                {"item": coin, "chance": 0.5},
            ],
            "instant_death": False,
            "point_value": 130,
            "pronouns": "it",
        },
        # Monster hunter ally
        "hunter": {
            "name": "hunter",
            "description": "A grizzled monster hunter nurses a drink, crossbow within reach.",
            "strength": 40,
            "dexterity": 35,
            "max_stamina": 100,
            "damage": 13,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": coin, "chance": 0.7},
            ],
            "instant_death": False,
            "point_value": 0,
            "pronouns": "he",
        },
        # ===== CASTLE RAVENLOFT =====
        # Stone gargoyle
        "gargoyle": {
            "name": "gargoyle",
            "description": "A stone gargoyle suddenly moves, revealing it was never truly stone at all.",
            "strength": 50,
            "dexterity": 25,
            "max_stamina": 120,
            "damage": 15,
            "aggressive": True,
            "aggro_delay_min": 2,
            "aggro_delay_max": 5,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": coin, "chance": 0.4},
            ],
            "instant_death": False,
            "point_value": 100,
            "pronouns": "it",
        },
        # Dungeon wraith
        "wraith": {
            "name": "wraith",
            "description": "A wraith, a creature of pure darkness and hatred, floats toward you radiating cold.",
            "strength": 45,
            "dexterity": 45,
            "max_stamina": 90,
            "damage": 16,
            "aggressive": True,
            "aggro_delay_min": 0,
            "aggro_delay_max": 1,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": essence, "chance": 0.9},
            ],
            "instant_death": False,
            "point_value": 120,
            "pronouns": "it",
        },
        # Vampire consort
        "consort": {
            "name": "consort",
            "description": "A vampire consort in decayed finery smiles beautifully, revealing gleaming fangs.",
            "strength": 55,
            "dexterity": 45,
            "max_stamina": 130,
            "damage": 18,
            "aggressive": True,
            "aggro_delay_min": 2,
            "aggro_delay_max": 4,
            "patrol_rooms": ["dining", "stairs"],
            "movement_interval": 150,
            "loot_table": [
                {"item": fang, "chance": 1.0},
                {"item": coin, "chance": 0.8},
                {"item": essence, "chance": 0.5},
            ],
            "instant_death": False,
            "point_value": 180,
            "pronouns": "she",
        },
        # STRAHD VON ZAROVICH - FINAL BOSS
        "strahd": {
            "name": "Strahd",
            "description": "Count Strahd von Zarovich stands before you, ancient and terrible. His eyes burn with cold fire.",
            "strength": 80,
            "dexterity": 60,
            "max_stamina": 300,
            "damage": 25,
            "aggressive": True,
            "aggro_delay_min": 3,
            "aggro_delay_max": 5,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": heart, "chance": 1.0},
                {"item": fang, "chance": 1.0},
                {"item": coin, "chance": 1.0},
                {"item": coin, "chance": 1.0},
                {"item": essence, "chance": 1.0},
            ],
            "instant_death": False,
            "point_value": 500,
            "pronouns": "he",
        },
        # Skeleton - instant death, found in crypts
        "skeleton": {
            "name": "skeleton",
            "description": "A brittle skeleton rattles to life, ancient bones held together by dark magic.",
            "strength": 20,
            "dexterity": 15,
            "max_stamina": 10,
            "damage": 6,
            "aggressive": True,
            "aggro_delay_min": 1,
            "aggro_delay_max": 2,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [
                {"item": skull, "chance": 0.9},
                {"item": coin, "chance": 0.3},
            ],
            "instant_death": True,
            "point_value": 25,
            "pronouns": "it",
        },
        # Prisoner in the Baron's dungeon
        "prisoner": {
            "name": "prisoner",
            "description": "A gaunt prisoner in tattered rags is bound to the wall with heavy chains.",
            "strength": 10,
            "dexterity": 10,
            "max_stamina": 30,
            "damage": 0,
            "aggressive": False,
            "aggro_delay_min": 0,
            "aggro_delay_max": 0,
            "patrol_rooms": [],
            "movement_interval": 0,
            "loot_table": [],
            "instant_death": False,
            "point_value": 0,
            "pronouns": "he",
        },
    }
