name: Deploy Backend to Cloud Run

on:
  push:
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify active account and configure Docker for Artifact Registry
        run: |
          echo "Active accounts:"
          gcloud auth list
          echo "Configuring Docker authentication for Artifact Registry..."
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          cd backend
          docker buildx build --platform linux/amd64 --push \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-mud-server:v${{ github.run_number }} .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-mud-service \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-mud-server:v${{ github.run_number }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --timeout=60s
